### ISSUE TITLE
The fix for 2.1.1 does not work as expected

### ISSUE THREAD

**Issue by sey** [Tim-Erwin/oauth2-pkce#4]
In `fetchAccessTokenUsingCode` the following part won't work.
```
const body = 'grant_type=authorization_code&'
  + `code=${encodeURIComponent(authorizationCode || '')}&`
  + `redirect_uri=${encodeURIComponent(redirectUrl)}&`
  + `client_id=${encodeURIComponent(clientId)}&`
  + `code_verifier=${codeVerifier}&`
  + oneTimeParams ? ('&' + objectToQueryString(oneTimeParams)) : '';
```

It is missing parenthesis to properly evaluate the ternary expression. Which ends up always evaluating to true, so you still need to pass an empty object. And now, even with the empty object you will always end up with a '&' string for the body.

Fixing the code in a more robust way would be as follows:

```
const formData = {
  grant_type: 'authorization_code',
  code: authorizationCode,
  redirect_uri: redirectUrl,
  client_id: clientId,
  code_verifier: codeVerifier,
  ...oneTimeParams
}

const body = new URLSearchParams(formData).toString();
```

**Comment by Archelyst** [comment]
Thank you @sey , I like your code. It's committed and published as version 2.1.3
